Hw5
lzbkln/java-course-tinkoff-spring-2024 pull request #5
Opened 2024-03-17 01:48 UTC by lzbkln

2024-03-19 14:49 UTC, lzbkln commented
Расширен функционал:
1. Оповещение о новых ветках
2. Оповещение о новых ответах на вопрос
Добавлен Jooq

2024-03-24 16:23 UTC, strelchm requested changes

2024-03-24 16:23 UTC, strelchm commented on scrapper/src/test/java/edu/java/scrapper/repository/jdbc/JdbcLinkRepositoryTest.java
> +        assertThat(actualSize).isNotNull();
Здесь проверяем примитив на null?

2024-03-24 16:23 UTC, strelchm commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +    public void saveLink(Long tgChatId, URI url) {
Почему этот метод не-transactional? Все действия по обновлению БД должны быть атомарными вместе. А у нас сейчас может одно дейтсвие пройти, а другой нет и будет неконсистентность

2024-03-27 18:56 UTC, strelchm requested changes

2024-03-27 18:56 UTC, strelchm commented on bot/src/main/java/edu/java/bot/controller/BotController.java
> +        linkUpdateService.sendMessage(linkUpdateRequest);
nit:  обычно в сервисы DTO не передают, а передают доменные объекты

2024-03-27 18:56 UTC, strelchm commented on scrapper/src/main/java/edu/java/clients/sites/linkCheckers/UpdateChecker.java
> +public abstract class UpdateChecker {
nit: почему не интерфейс?

2024-03-27 18:56 UTC, strelchm commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcStackOverflowQuestionRepository.java
> +    private static final RowMapper<StackOverflowQuestion> ROW_MAPPER = new StackOverflowQuestionRowMapper();
Почему не сделать бином?

2024-03-27 18:56 UTC, strelchm commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcStackOverflowQuestionRepository.java
> +    private static final RowMapper<StackOverflowQuestion> ROW_MAPPER = new StackOverflowQuestionRowMapper();
Удобнее это сделать, если пометим @Repository бин, а не будем в конфигурации создавать @Bean. Сервисы можно помечать @Service. Другие классы - @Component. Плюс такого задания - инжектятся бины через конструктор и не надо их указывать явно, как в @Configuration (последняя лучше для конфигураций)

2024-03-27 18:56 UTC, strelchm commented on scrapper/src/main/java/edu/java/service/jooq/JooqLinkService.java
> +    private void checkRegisterChat(Long chatId) {
nit: По неймингу: check - это про возврат boolan. По идеологии spring-репозиториев find - это возврат optional, т е либо объект либо null. А вот get - это либо возвратить объект, либо ошибку прокинуть, что нету в БД

2024-04-06 16:33 UTC, strelchm approved these changes

2024-04-06 17:25 UTC, merged

2024-04-06 17:28 UTC, strelchm commented on scrapper/src/main/java/edu/java/repository/LinkRepository.java
> +    boolean findByUrlBool(String url);
nit: **find** - больше про достование сущности. Лучше **existsByUrl**